name: Argon2 Linux ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/argon2-linux-arm.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y gcc-aarch64-linux-gnu git make
          git clone --recursive --branch 20190702 https://github.com/P-H-C/phc-winner-argon2.git
          cd phc-winner-argon2
          make CC=aarch64-linux-gnu-gcc OPTTARGET=armv8-a
          mv libargon2.so.1 libargon2.arm64.so
      - uses: actions/upload-artifact@v4
        with:
          name: libargon2.arm64.so
          path: phc-winner-argon2/libargon2.arm64.so
