name: Argon2 Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/argon2-mac.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          git clone --recursive --branch 20190702 https://github.com/P-H-C/phc-winner-argon2.git
          cd phc-winner-argon2

          make OPTTARGET=nehalem
          mv libargon2.1.dylib /tmp/libargon2.x86_64.dylib

          make clean

          make OPTTEST=1 CFLAGS="-target arm64-apple-macos11 -march=armv8-a"
          mv libargon2.1.dylib /tmp/libargon2.arm64.dylib

          lipo -create -output /tmp/libargon2.dylib /tmp/libargon2.x86_64.dylib /tmp/libargon2.arm64.dylib
          lipo -archs /tmp/libargon2.dylib
          file /tmp/libargon2.dylib

          du -ah .
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v1
        with:
          name: libargon2.dylib
          path: /tmp/libargon2.dylib
      - uses: actions/upload-artifact@v1
        with:
          name: libargon2.x86_64.dylib
          path: /tmp/libargon2.x86_64.dylib
      - uses: actions/upload-artifact@v1
        with:
          name: libargon2.arm64.dylib
          path: /tmp/libargon2.arm64.dylib
