name: Argon2 Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/argon2-mac.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          git clone --recursive --branch 20190702 https://github.com/P-H-C/phc-winner-argon2.git
          cd phc-winner-argon2
          make OPTTARGET=nehalem
          mv libargon2.1.dylib libargon2.dylib
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v4
        with:
          name: libargon2.dylib
          path: phc-winner-argon2/libargon2.dylib
