name: BlingFire Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/blingfire-mac.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          brew install cmake
          git clone --recursive --branch v0.1.8 https://github.com/microsoft/BlingFire.git
          cd BlingFire
          mkdir build
          cd build
          cmake ..
          make
          cd ..
          du -ah .
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v4
        with:
          name: libblingfiretokdll.dylib
          path: BlingFire/build/libblingfiretokdll.dylib
