name: cmfrec Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/cmfrec-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    timeout-minutes: 5
    steps:
      - run: |
          apt update
          apt install -y build-essential git libblas-dev liblapack-dev wget
          wget -q https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-linux-x86_64.tar.gz
          tar xzf cmake-3.21.3-linux-x86_64.tar.gz
          git clone --recursive --branch master https://github.com/david-cortes/cmfrec.git
          cd cmfrec
          git checkout ccdd1d44c3a496c6b0e688a8f69dbf16011dd324
          ../cmake-3.21.3-linux-x86_64/bin/cmake -B build
          ../cmake-3.21.3-linux-x86_64/bin/cmake --build build

          mkdir dist
          cp build/libcmfrec.so dist
          cp LICENSE dist/LICENSE
          cp inst/COPYRIGHTS dist/COPYRIGHTS
      - uses: actions/upload-artifact@v4
        with:
          name: cmfrec-3.4.2-x86_64-linux
          path: cmfrec/dist
