name: cmfrec Mac ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/cmfrec-mac-arm.yml

jobs:
  build:
    runs-on: macos-11
    steps:
      - run: |
          git clone --recursive --branch master https://github.com/david-cortes/cmfrec.git
          cd cmfrec
          git checkout 9affd9adc908f7751c02af9a4ed12ccffe5ec080
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_ARCHITECTURES=arm64
          make
          mv libcmfrec.dylib libcmfrec.arm64.dylib
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
      - uses: actions/upload-artifact@v2
        with:
          name: libcmfrec.arm64.dylib
          path: cmfrec/build/libcmfrec.arm64.dylib
