name: cmfrec Mac ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/cmfrec-mac-arm.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          git clone --recursive --branch master https://github.com/david-cortes/cmfrec.git
          cd cmfrec
          git checkout ccdd1d44c3a496c6b0e688a8f69dbf16011dd324
          cmake -B build -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_ARCHITECTURES=arm64
          cmake --build build

          mkdir dist
          cp build/libcmfrec.dylib dist
          cp LICENSE dist/LICENSE
          cp inst/COPYRIGHTS dist/COPYRIGHTS
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
      - uses: actions/upload-artifact@v4
        with:
          name: cmfrec-3.4.2-aarch64-darwin
          path: cmfrec/dist
