name: cmfrec Mac ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/cmfrec-mac-arm.yml

jobs:
  build:
    runs-on: macos-11.0
    steps:
      - run: |
          git clone --recursive --branch master https://github.com/david-cortes/cmfrec.git
          cd cmfrec
          git checkout 439782c23765b97879c6b05bbdba329996c3ceb6
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_ARCHITECTURES=arm64
          make
          file libcmfrec.dylib
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
      - uses: actions/upload-artifact@v2
        with:
          name: libcmfrec.dylib
          path: cmfrec/build/libcmfrec.dylib
