name: cmfrec Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/cmfrec-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    timeout-minutes: 5
    steps:
      - run: |
          apt update
          apt install -y build-essential git libblas-dev liblapack-dev wget
          wget -q https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-linux-x86_64.tar.gz
          tar xzf cmake-3.21.3-linux-x86_64.tar.gz
          git clone --recursive --branch master https://github.com/david-cortes/cmfrec.git
          cd cmfrec
          git checkout 9affd9adc908f7751c02af9a4ed12ccffe5ec080
          mkdir build
          cd build
          ../../cmake-3.21.3-linux-x86_64/bin/cmake ..
          make
      - uses: actions/upload-artifact@v2
        with:
          name: libcmfrec.so
          path: cmfrec/build/libcmfrec.so
