name: Interpret Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/interpret-mac.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          git clone --recursive --branch v0.2.7 https://github.com/interpretml/interpret.git
          cd interpret
          sh build.sh
          du -ah .
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v4
        with:
          name: lib_ebm_native_mac_x64.dylib
          path: interpret/staging/lib_ebm_native_mac_x64.dylib
