name: Interpret Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/interpret-linux.yml

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - run: |
          git clone --recursive --branch v0.2.3 https://github.com/interpretml/interpret.git
          cd interpret
          sh build.sh
          du -ah .
      - uses: actions/upload-artifact@v2
        with:
          name: lib_ebm_native_linux_x64.so
          path: interpret/staging/lib_ebm_native_linux_x64.so
