name: LIBMF Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/libmf-mac.yml

jobs:
  build:
    runs-on: macos-15-intel
    steps:
      - run: |
          git clone https://github.com/ankane/libmf-fork.git libmf
          cd libmf
          git checkout 3d5570a1fc28e7a0def51a048b256bb936c8b73e
          sed -i '' 's/-march=native/-march=nehalem/g' Makefile
          make all lib DFLAG="" OMPFLAG=""
          mv libmf.2.dylib libmf.dylib
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
      - uses: actions/upload-artifact@v7
        with:
          name: libmf.dylib
          path: libmf/libmf.dylib
