name: LightGBM Linux ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/lightgbm-linux-arm.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y cmake gcc-aarch64-linux-gnu g++-aarch64-linux-gnu git
          git clone --recursive --branch v4.3.0 https://github.com/microsoft/LightGBM
          cd LightGBM
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=arm -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY
          make -j4
          cd ..
          mv lib_lightgbm.so lib_lightgbm.arm64.so
      - uses: actions/upload-artifact@v3
        with:
          name: lib_lightgbm.arm64.so
          path: LightGBM/lib_lightgbm.arm64.so
