name: LightGBM Linux ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/lightgbm-linux-arm.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - run: |
          apt update
          apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu git make wget
          wget -q https://github.com/Kitware/CMake/releases/download/v3.28.1/cmake-3.28.1-linux-x86_64.tar.gz
          tar xzf cmake-3.28.1-linux-x86_64.tar.gz
          git clone --recursive --branch v4.6.0 https://github.com/microsoft/LightGBM
          cd LightGBM
          mkdir build
          cd build
          ../../cmake-3.28.1-linux-x86_64/bin/cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=arm -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY
          make -j4
          cd ..
          mv lib_lightgbm.so lib_lightgbm.arm64.so
      - uses: actions/upload-artifact@v4
        with:
          name: lib_lightgbm.arm64.so
          path: LightGBM/lib_lightgbm.arm64.so
