name: MITIE Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/mitie-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y build-essential cmake git
          git clone --recursive --branch v0.7 https://github.com/mit-nlp/MITIE.git
          cd MITIE/mitielib
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON
          make -j4
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v4
        with:
          name: libmitie.so
          path: MITIE/mitielib/build/libmitie.so
