name: MITIE Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/mitie-mac.yml

jobs:
  build:
    runs-on: macos-11.0
    steps:
      - run: |
          brew install cmake
          git clone --recursive --branch v0.7 https://github.com/mit-nlp/MITIE.git
          cd MITIE/mitielib
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          make -j4
          file libmitie.dylib
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v1
        with:
          name: libmitie.dylib
          path: MITIE/mitielib/build/libmitie.dylib
