name: Multicore t-SNE Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/multicore-tsne-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y build-essential cmake git
          git clone --recursive --branch master https://github.com/DmitryUlyanov/Multicore-TSNE.git
          cd Multicore-TSNE/multicore_tsne
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release
          make -j4
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v4
        with:
          name: libtsne_multicore.so
          path: Multicore-TSNE/multicore_tsne/build/libtsne_multicore.so
