name: Multicore t-SNE Linux ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/multicore-tsne-linux-arm.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - run: |
          apt update
          apt install -y cmake gcc-aarch64-linux-gnu g++-aarch64-linux-gnu git
          git clone --recursive --branch master https://github.com/DmitryUlyanov/Multicore-TSNE.git
          cd Multicore-TSNE/multicore_tsne
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=arm -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY
          make -j4
          mv libtsne_multicore.so libtsne_multicore.arm64.so
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v4
        with:
          name: libtsne_multicore.arm64.so
          path: Multicore-TSNE/multicore_tsne/build/libtsne_multicore.arm64.so
