name: NGT Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/ngt-linux.yml

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - run: |
          sudo apt install cmake
          git clone --recursive --branch v1.12.2 https://github.com/yahoojapan/NGT
          cd NGT
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DNGT_MARCH_NATIVE_DISABLED=ON -DNGT_OPENMP_DISABLED=ON
          make -j4
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v2
        with:
          name: libngt.so
          path: NGT/build/lib/NGT/libngt.so.1.12.2
