name: NGT Windows
on:
  push:
    paths:
    - .github/workflows/ngt-windows.yml

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          git clone --recursive --branch v1.9.0 https://github.com/yahoojapan/NGT
          cd NGT
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64
           "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\16.0\Bin\MSBuild.exe" ngt.sln /p:Configuration=Release
          ls
          ls lib
          ls lib/NGT
        shell: cmd
      - uses: actions/upload-artifact@v1
        with:
          name: ngt.dll
          path: NGT/build/lib/NGT/ngt.dll.1.9.0
