name: NGT Linux
on:
  push:
    paths:
    - .github/workflows/ngt-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install cmake
          git clone --recursive --branch v1.9.0 https://github.com/yahoojapan/NGT
          cd NGT
          mkdir build
          cd build
          cmake ..
          make -j4
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v1
        with:
          name: libngt.so
          path: NGT/build/lib/NGT/libngt.so.1.9.0
