name: NGT Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/ngt-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      # half license from https://sourceforge.net/p/half/code/HEAD/tree/tags/release-2.2.0/LICENSE.txt
      # grep checks source code version
      - run: |
          apt update
          apt install -y build-essential cmake git

          git clone --recursive --branch v1.14.6 https://github.com/yahoojapan/NGT
          cd NGT
          cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE=ON -DNGT_MARCH_NATIVE_DISABLED=ON
          cmake --build build

          grep -F "Version 2.2.0" lib/NGT/half.hpp

          mkdir dist
          cp build/lib/NGT/libngt.so dist
          cp LICENSE dist/LICENSE-ngt.txt
          cp ../extra/NGT/LICENSE-half.txt dist
      - uses: actions/upload-artifact@v3
        with:
          name: ngt-1.14.6-x86_64-linux
          path: NGT/dist
