name: OSQP Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/osqp-mac.yml

jobs:
  build:
    runs-on: macos-13
    steps:
      - run: |
          git clone --recursive --branch v1.0.0 https://github.com/oxfordcontrol/osqp.git
          cd osqp
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON
          make -j4
          file out/libosqp.dylib
          cd ..

          mkdir dist
          cp build/out/libosqp.dylib dist
          cp LICENSE dist/LICENSE-osqp.txt
          cp NOTICE dist/NOTICE-osqp.txt
          cp algebra/_common/lin_sys/qdldl/amd/LICENSE dist/LICENSE-amd.txt
          cp build/_deps/qdldl-src/LICENSE dist/LICENSE-qdldl.txt
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
      - uses: actions/upload-artifact@v4
        with:
          name: osqp-1.0.0-x86_64-darwin
          path: osqp/dist
