name: OSQP Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/osqp-mac.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          git clone --recursive --branch v0.6.2 https://github.com/oxfordcontrol/osqp.git
          cd osqp
          mkdir build
          cd build
          cmake .. -DENABLE_MKL_PARDISO=OFF -G "Unix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON
          make -j4
          file out/libosqp.dylib
          cd ..

          mkdir dist
          cp build/out/libosqp.dylib dist
          cp LICENSE dist/LICENSE-osqp.txt
          cp NOTICE dist/NOTICE-osqp.txt
          cp lin_sys/direct/qdldl/amd/LICENSE dist/LICENSE-amd.txt
          cp lin_sys/direct/qdldl/qdldl_sources/LICENSE dist/LICENSE-qdldl.txt
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v3
        with:
          name: osqp-0.6.2-x86_64-darwin
          path: osqp/dist
