name: Prophet Linux ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/prophet-linux-arm.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu python3-pip wget

          pip3 install strata-cli

          wget -q https://github.com/facebook/prophet/archive/refs/tags/v1.1.tar.gz
          tar xzf v1.1.tar.gz
          cp prophet-1.1/python/stan/prophet.stan .

          strata prophet.stan -o dist --cross-compile
          cp prophet-1.1/LICENSE dist/licenses/prophet-license.txt
      - uses: actions/upload-artifact@v4
        with:
          name: prophet-1.1-aarch64-linux
          path: dist
