name: Prophet Linux ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/prophet-linux-arm.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu make wget chrpath

          wget -q https://github.com/stan-dev/cmdstan/releases/download/v2.29.2/cmdstan-2.29.2-linux-arm64.tar.gz
          tar xzf cmdstan-2.29.2-linux-arm64.tar.gz
          cd cmdstan-2.29.2

          wget -q https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2020.3.tar.gz
          tar xzf v2020.3.tar.gz
          cd oneTBB-2020.3
          make arch=arm CONLY=aarch64-linux-gnu-gcc CPLUS=aarch64-linux-gnu-g++
          mkdir lib
          cp build/**/*.so* lib
          cd ..

          wget -q https://github.com/stan-dev/stanc3/releases/download/v2.29.2/linux-stanc
          cp linux-stanc bin/linux-stanc

          wget -q https://github.com/facebook/prophet/archive/refs/tags/v1.0.tar.gz
          tar xzf v1.0.tar.gz
          cp prophet-1.0/python/stan/unix/prophet.stan .
          make prophet TBB_INC=oneTBB-2020.3/include TBB_LIB=oneTBB-2020.3/lib PRECOMPILED_HEADERS=false CXXFLAGS_EIGEN="-DEIGEN_MPL2_ONLY" CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ OS=Linux

          mkdir output

          mkdir output/bin
          cp prophet output/bin
          chrpath -r '$ORIGIN/../lib' output/bin/prophet

          mkdir output/lib
          cp oneTBB-2020.3/lib/*.so* output/lib
          strip --strip-debug output/lib/*.so.2

          mkdir output/licenses
          cp prophet-1.0/LICENSE output/licenses/prophet-license.txt
          cp LICENSE output/licenses/cmdstan-license.txt
          cp stan/LICENSE.md output/licenses/stan-license.txt
          cp stan/lib/stan_math/LICENSE.md output/licenses/stan-math-license.txt
          cp stan/lib/stan_math/licenses/boost-license.txt output/licenses
          cp stan/lib/stan_math/licenses/sundials-license.txt output/licenses
          cp stan/lib/stan_math/licenses/tbb-license.txt output/licenses
          cp stan/lib/stan_math/lib/eigen_3.3.9/COPYING.MPL2 output/licenses/eigen-mpl2-license.txt
          cp stan/lib/stan_math/lib/eigen_3.3.9/COPYING.BSD output/licenses/eigen-bsd-license.txt
          cp oneTBB-2020.3/third-party-programs.txt output/licenses/tbb-third-party-programs.txt

          wget -q https://github.com/CLIUtils/CLI11/archive/refs/tags/v1.9.1.tar.gz
          tar xzf v1.9.1.tar.gz
          cp CLI11-1.9.1/LICENSE output/licenses/cli11-license.txt

          wget -q https://github.com/Tencent/rapidjson/archive/refs/tags/v1.1.0.tar.gz
          tar xzf v1.1.0.tar.gz
          cp rapidjson-1.1.0/license.txt output/licenses/rapidjson-license.txt
      - uses: actions/upload-artifact@v3
        with:
          name: prophet-linux-arm
          path: cmdstan-2.29.2/output
