name: Prophet Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/prophet-mac.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          pip3 install strata-cli

          wget -q https://github.com/facebook/prophet/archive/refs/tags/v1.0.tar.gz
          tar xzf v1.0.tar.gz
          cp prophet-1.0/python/stan/unix/prophet.stan .

          strata prophet.stan -o dist
          cp prophet-1.0/LICENSE dist/licenses/prophet-license.txt
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v3
        with:
          name: prophet-1.0-x86_64-darwin
          path: dist
