name: RDKit Windows
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/rdkit-windows.yml

jobs:
  build:
    runs-on: windows-2022
    steps:
      - run: |
          curl -L -o boost.7z https://github.com/boostorg/boost/releases/download/boost-1.85.0/boost-1.85.0-b2-nodocs.7z
          7z x boost.7z

          git clone --recursive --branch Release_2024_03_6 https://github.com/rdkit/rdkit.git
          cd rdkit
          ls ../boost-1.85.0
          cmake -S . -B build -DBoost_ROOT=../boost-1.85.0 -DCMAKE_POLICY_DEFAULT_CMP0167=OLD -DCMAKE_BUILD_TYPE=Release -DRDK_BUILD_CFFI_LIB=ON -DRDK_BUILD_COORDGEN_SUPPORT=OFF -DRDK_BUILD_CPP_TESTS=OFF -DRDK_BUILD_DESCRIPTORS3D=OFF -DRDK_BUILD_FREETYPE_SUPPORT=OFF -DRDK_BUILD_INCHI_SUPPORT=OFF -DRDK_BUILD_MAEPARSER_SUPPORT=OFF -DRDK_BUILD_PYTHON_WRAPPERS=OFF -DRDK_BUILD_QT_SUPPORT=OFF -DRDK_BUILD_SLN_SUPPORT=OFF -DRDK_OPTIMIZE_POPCNT=OFF -DRDK_TEST_MMFF_COMPLIANCE=OFF -DRDK_TEST_MULTITHREADED=OFF -DRDK_USE_BOOST_IOSTREAMS=OFF -DRDK_USE_BOOST_SERIALIZATION=OFF -DRDK_USE_BOOST_STACKTRACE=OFF -DRDK_USE_URF=OFF
          cmake --build build --config Release --parallel 4

          mkdir dist
          ls build/bin/Release
          cp build/bin/Release/rdkitcffi.dll dist/rdkitcffi.dll
          cp license.txt dist/rdkit-license.txt
          cp Code/GraphMol/ChemReactions/license.txt dist/ChemReactions-license.txt
          cp External/rapidjson-1.1.0/license.txt dist/rapidjson-license.txt
        shell: cmd
      - uses: actions/upload-artifact@v4
        with:
          name: rdkit-2024.03.6-x86_64-windows
          path: rdkit/dist
