name: SCS Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/scs-mac.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          git clone --recursive --branch v2.1.2 https://github.com/cvxgrp/scs.git
          cd scs
          make
          du -ah .
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v4
        with:
          name: libscsindir.dylib
          path: scs/out/libscsindir.dylib
      - uses: actions/upload-artifact@v4
        with:
          name: libscsdir.dylib
          path: scs/out/libscsdir.dylib
