name: SCS Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/scs-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y build-essential git libblas-dev liblapack-dev make
          git clone --recursive --branch v2.1.2 https://github.com/cvxgrp/scs.git
          cd scs
          make
          du -ah .
      - uses: actions/upload-artifact@v4
        with:
          name: libscsindir.so
          path: scs/out/libscsindir.so
      - uses: actions/upload-artifact@v4
        with:
          name: libscsdir.so
          path: scs/out/libscsdir.so
