name: ThunderSVM Mac ARM
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/thundersvm-mac-arm.yml

jobs:
  build:
    runs-on: macos-11.0
    steps:
      - run: |
          cd /tmp
          wget -q -O libomp.tar.gz https://bintray.com/homebrew/bottles/download_file?file_path=libomp-$LIBOMP_VERSION.arm64_big_sur.bottle.tar.gz
          tar xzf libomp.tar.gz
          sudo mkdir -p /opt/homebrew/opt
          sudo chown $USER /opt/homebrew/opt
          cp -r libomp/$LIBOMP_VERSION /opt/homebrew/opt/libomp
          find /opt/homebrew
        env:
          LIBOMP_VERSION: 11.1.0
      - run: |
          git clone --recursive --branch master https://github.com/Xtra-Computing/thundersvm
          cd thundersvm
          mkdir build
          cd build
          cmake .. -DUSE_CUDA=OFF -DCMAKE_CXX_FLAGS=-march=armv8-a -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_OSX_ARCHITECTURES=arm64 -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include" -DOpenMP_C_LIB_NAMES=omp -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include" -DOpenMP_CXX_LIB_NAMES=omp -DOpenMP_omp_LIBRARY=/opt/homebrew/opt/libomp/lib/libomp.dylib
          make -j4
          file lib/libthundersvm.dylib
          install_name_tool -change @@HOMEBREW_PREFIX@@/opt/libomp/lib/libomp.dylib /opt/homebrew/opt/libomp/lib/libomp.dylib lib/libthundersvm.dylib
          otool -L lib/libthundersvm.dylib
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
      - uses: actions/upload-artifact@v2
        with:
          name: libthundersvm.dylib
          path: thundersvm/build/lib/libthundersvm.dylib
