name: ThunderSVM Windows
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/thundersvm-windows.yml

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          git clone --recursive --branch master https://github.com/Xtra-Computing/thundersvm
          cd thundersvm
          mkdir build
          cd build
          cmake .. -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -DUSE_CUDA=OFF -G "Visual Studio 16 2019" -A x64
          cmake --build . --config Release
        shell: cmd
      - uses: actions/upload-artifact@v4
        with:
          name: thundersvm.dll
          path: thundersvm\build\bin\Release\thundersvm.dll
