name: ThunderSVM Windows
on:
  push:
    paths:
    - .github/workflows/thundersvm-windows.yml

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          git clone --recursive --branch v0.3.4 https://github.com/Xtra-Computing/thundersvm
          cd thundersvm
          mkdir build
          cd build
          cmake .. -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -DUSE_CUDA=OFF -DUSE_EIGEN=ON -G "Visual Studio 16 2019" -A x64
          cmake --build . --config Release
        shell: cmd
      - uses: actions/upload-artifact@v1
        with:
          name: thundersvm.dll
          path: thundersvm\build\bin\Release\thundersvm.dll
