name: ThunderSVM Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/thundersvm-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y build-essential git wget
          wget -q https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-linux-x86_64.tar.gz
          tar xzf cmake-3.21.3-linux-x86_64.tar.gz
          git clone --recursive --branch master https://github.com/Xtra-Computing/thundersvm
          cd thundersvm
          mkdir build
          cd build
          ../../cmake-3.21.3-linux-x86_64/bin/cmake .. -DUSE_CUDA=OFF -DCMAKE_CXX_FLAGS=-march=x86-64 -DCMAKE_VERBOSE_MAKEFILE=ON
          make -j4
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v4
        with:
          name: libthundersvm.so
          path: thundersvm/build/lib/libthundersvm.so
