name: Vowpal Wabbit Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/vowpalwabbit-mac.yml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          brew install cmake boost
          git clone --recursive --branch 8.8.1 https://github.com/VowpalWabbit/vowpal_wabbit.git
          cd vowpal_wabbit
          mkdir build
          cd build
          cmake ..
          make -j4
          cd ..
          du -ah .
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
      - uses: actions/upload-artifact@v4
        with:
          name: libvw_c_wrapper.dylib
          path: vowpal_wabbit/build/vowpalwabbit/libvw_c_wrapper.dylib
