name: Vowpal Wabbit Mac
on:
  push:
    paths:
    - .github/workflows/vowpalwabbit-mac.yml

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - run: |
          brew install cmake boost
          git clone --recursive --branch 8.8.0 https://github.com/VowpalWabbit/vowpal_wabbit.git
          cd vowpal_wabbit
          mkdir build
          cd build
          cmake .. -DSTATIC_LINK_VW=ON
          make -j4
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v1
        with:
          name: libvw_c_wrapper.a
          path: vowpal_wabbit/build/vowpalwabbit/libvw_c_wrapper.a
