name: XGBoost Linux
on:
  push:
    paths:
    - .github/workflows/xgboost-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install cmake
          git clone --recursive --branch v0.90 https://github.com/dmlc/xgboost
          cd xgboost
          mkdir build
          cd build
          cmake ..
          make -j4
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v1
        with:
          name: libxgboost.so
          path: xgboost/lib/libxgboost.so
