name: XGBoost Linux
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install cmake
          git clone --recursive https://github.com/dmlc/xgboost
          cd xgboost
          mkdir build
          cd build
          cmake ..
          make -j4
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v1
        with:
          name: libxgboost.so
          path: lib/libxgboost.so
