name: XGBoost Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/xgboost-linux.yml

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - run: |
          sudo apt install cmake
          git clone --recursive --branch v1.1.0 https://github.com/dmlc/xgboost
          cd xgboost
          mkdir build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON
          make -j4
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v1
        with:
          name: libxgboost.so
          path: xgboost/lib/libxgboost.so
