name: XGBoost Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/xgboost-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - run: |
          apt update
          apt install -y build-essential git wget
          wget -q https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-linux-x86_64.tar.gz
          tar xzf cmake-3.21.3-linux-x86_64.tar.gz
          git clone --recursive --branch v1.7.5 https://github.com/dmlc/xgboost
          cd xgboost
          mkdir build
          cd build
          ../../cmake-3.21.3-linux-x86_64/bin/cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON
          make -j4
          cd ..
          du -ah .

          mkdir dist
          cp lib/libxgboost.so dist
          cp LICENSE dist/LICENSE-xgboost.txt
          cp dmlc-core/LICENSE dist/LICENSE-dmlc-core.txt
          cp rabit/LICENSE dist/LICENSE-rabit.txt
      - uses: actions/upload-artifact@v3
        with:
          name: xgboost-1.7.0-x86_64-linux
          path: xgboost/dist
