name: XGBoost Linux
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/xgboost-linux.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - run: |
          apt update
          apt install -y build-essential cmake git wget
          wget -q https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-linux-x86_64.tar.gz
          tar xzf cmake-3.21.3-linux-x86_64.tar.gz
          git clone --recursive --branch v1.4.0 https://github.com/dmlc/xgboost
          cd xgboost
          mkdir build
          cd build
          ../../cmake-3.21.3-linux-x86_64/bin/cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON
          make -j4
          cd ..
          du -ah .
      - uses: actions/upload-artifact@v2
        with:
          name: libxgboost.so
          path: xgboost/lib/libxgboost.so
