name: xLearn Windows
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/xlearn-windows.yml

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          git clone --branch v0.4.4 https://github.com/aksnzhy/xlearn.git
          cd xlearn
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64
          cmake --build . --config Release
        shell: cmd
      - uses: actions/upload-artifact@v4
        with:
          name: xlearn_api.dll
          path: xlearn\build\test\c_api\Release\xlearn_api.dll
