name: xLearn Windows
on:
  push:
    paths:
    - .github/workflows/xlearn-windows.yml

jobs:
  build:
    runs-on: windows-2016
    steps:
      - run: |
          git clone --branch v0.4.4 https://github.com/aksnzhy/xlearn.git
          cd xlearn
          mkdir build
          cd build
          cmake -G "Visual Studio 15 Win64" ../
          MSBuild xLearn.sln /p:Configuration=Release
      - uses: actions/upload-artifact@v1
        with:
          name: libxlearn_api.dll
          path: xlearn/build/lib/libxlearn_api.dll
