name: xLearn Windows
on:
  push:
    paths:
    - .github/workflows/xlearn-windows.yml

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          git clone --branch v0.4.4 https://github.com/aksnzhy/xlearn.git
          cd xlearn
          mkdir build
          cd build -G "Visual Studio 16 Win64" ../
          \"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat\" x64
          MSBuild xLearn.sln /p:Configuration=Release
      - uses: actions/upload-artifact@v1
        with:
          name: libxlearn_api.dll
          path: xlearn/build/lib/libxlearn_api.dll
